[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/github-callback"
  to = "/"
  status = 200

[[redirects]]
  from = "/github-callback/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 