name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          echo "Installed dependencies successfully"
      
      - name: Install image processing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev libjpeg-dev
          echo "Image processing libraries installed"
          
      - name: Build
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed successfully"
        env:
          NODE_ENV: production
          # This tells our config this is a GitHub Pages build
          DEPLOY_ENV: github
          VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Verify build output
        run: |
          echo "Verifying build output..."
          if [ ! -d "./dist" ]; then
            echo "Error: dist directory not found"
            exit 1
          fi
          echo "dist directory exists"
          ls -la ./dist
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 